client_id: '3MVG9A2kN3Bn17hs7B6KXIh3p.McgSl_QlOj6fA1OP5gird0ghBKWAwP0qrWYfAeJtWR5d9wnPRlzNqQZk2Nk'
client_secret: '1731644857108024694'
username: 'jimdev@sevenpoints.co'
password: 'mcgrath67nusOkUdvVsNqTVZoKkKeZcGU5'
debugging: true